### ISSUE TITLE
error right after install 

### ISSUE THREAD

**Issue by longtth** [traviskaufman/node-lipsum#10]
## issue 

node-lipsum throw exception right after install 

## steps 

1. install node-lipsum by `npm install -g node-lipsum` 
2. run `node-lipsum` from CLI 

## log

```console
# long-nguyenxuan @ long-nguyenxuan-homepc in ~ [18:52:12]
$ npm install -g node-lipsum
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

added 7 packages, and audited 8 packages in 5s

4 vulnerabilities (2 moderate, 2 high)

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

# long-nguyenxuan @ long-nguyenxuan-homepc in ~ [18:52:23]
$ node-lipsum
C:\Users\long-nguyenxuan\AppData\Roaming\npm\node_modules\node-lipsum\lib\lipsum.js:89
    throw new Error("Parser Error: " + err.message);
    ^

Error: Parser Error: undefined
    at Lipsum.parserErrorCallBack (C:\Users\long-nguyenxuan\AppData\Roaming\npm\node_modules\node-lipsum\lib\lipsum.js:89:11)
    at LipsumParser._error (C:\Users\long-nguyenxuan\AppData\Roaming\npm\node_modules\node-lipsum\lib\parser.js:131:5)
    at LipsumParser._error (C:\Users\long-nguyenxuan\AppData\Roaming\npm\node_modules\node-lipsum\lib\parser.js:12:59)
    at LipsumParser.parse (C:\Users\long-nguyenxuan\AppData\Roaming\npm\node_modules\node-lipsum\lib\parser.js:100:14)
    at LipsumParser.parse (C:\Users\long-nguyenxuan\AppData\Roaming\npm\node_modules\node-lipsum\lib\parser.js:12:59)
    at Lipsum.serviceCallback (C:\Users\long-nguyenxuan\AppData\Roaming\npm\node_modules\node-lipsum\lib\lipsum.js:97:35)
    at C:\Users\long-nguyenxuan\AppData\Roaming\npm\node_modules\node-lipsum\lib\lipsum.js:11:59
    at IncomingMessage.<anonymous> (C:\Users\long-nguyenxuan\AppData\Roaming\npm\node_modules\node-lipsum\lib\service.js:49:16)
    at IncomingMessage.emit (node:events:381:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
```

**Comment by traviskaufman** [comment]
Today, I published a new, fully-modernized version, which I believe should fix this issue. Please let me know if it does and I will close. Thank you for using node-lipsum 😃 .

**Comment by stormsnsnow** [comment]
Works now, thanks!
