### ISSUE TITLE
No functions work correctly

### ISSUE THREAD

**Issue by thepeanutman98** [traviskaufman/node-lipsum#4]
Not sure what the error is. All functions I have tried produce the same error message. Even just running the CLI gives this (with my username replaced with -----):

C:\>node-lipsum
C:\Users\-----\AppData\Roaming\npm\node_modules\node-lipsum\lib\lipsum.js:89
    throw new Error("Parser Error: " + err.message);
    ^

Error: Parser Error: undefined
    at Lipsum.parserErrorCallBack (C:\Users\-----\AppData\Roaming\npm\node_module
s\node-lipsum\lib\lipsum.js:89:11)
    at LipsumParser._error (C:\Users\-----\AppData\Roaming\npm\node_modules\node-
lipsum\lib\parser.js:131:5)
    at LipsumParser._error (C:\Users\-----\AppData\Roaming\npm\node_modules\node-
lipsum\lib\parser.js:12:59)
    at LipsumParser.parse (C:\Users\-----\AppData\Roaming\npm\node_modules\node-l
ipsum\lib\parser.js&#58;&nbsp;100&#58;14)
    at LipsumParser.parse (C:\Users\-----\AppData\Roaming\npm\node_modules\node-l
ipsum\lib\parser.js:12:59)
    at Lipsum.serviceCallback (C:\Users\-----\AppData\Roaming\npm\node_modules\no
de-lipsum\lib\lipsum.js:97:35)
    at C:\Users\-----\AppData\Roaming\npm\node_modules\node-lipsum\lib\lipsum.js:
11:59
    at IncomingMessage.<anonymous> (C:\Users\-----\AppData\Roaming\npm\node_modul
es\node-lipsum\lib\service.js:49:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

**Comment by ArK7652** [comment]
I am getting the same error, I think this is deprecated.

**Comment by YosepRA** [comment]
I'm getting the same error as well.

**Comment by traviskaufman** [comment]
Hey all,

Sorry I've been silent on this. I haven't really touched this code in a few years, and currently don't think I have the cycles to maintain. I'll leave this comment open and if someone wants to take over maintenance, I'm happy to get in touch with them and make that happen 😄

**Comment by traviskaufman** [comment]
Today, I published a new, fully-modernized version, which I believe should fix this issue. Please let me know if it does and I will close. Thank you for using node-lipsum 😃
